function R = run_HCL_ATTRIBUTION_DEV_V1()
% RUN_HCL_ATTRIBUTION_DEV_V1
%
% Generate independent development-stage HCL attribution states
% for the calibrated-flat reviewer control.
%
% Frozen protocol:
%   DEV seeds     : 20261001:20261005
%   Scenarios     : EB / ES / BS / EBS
%   Total states  : 5 x 4 = 20
%
% IMPORTANT:
%   - HCL configuration is NOT retuned here.
%   - No confirmation data are used.
%   - No recovery baseline needs to be rerun.
%   - D/H/M are saved in exactly the same format as the
%     independent confirmation experiment.

fprintf('\n');
fprintf('============================================================\n');
fprintf('HCL ATTRIBUTION DEV V1\n');
fprintf('Independent calibration-state generation\n');
fprintf('============================================================\n');

%% ============================================================
% 1. Load the SAME frozen final configuration
% =============================================================

C = HCL_DSP_FINAL_config();

devSeeds = C.developmentSeeds;
confirmSeeds = C.confirmationSeeds;

scenarios = {'EB','ES','BS','EBS'};

%% ============================================================
% 2. Protocol integrity checks
% =============================================================

assert(isequal(devSeeds,20261001:20261005), ...
    ['Development seeds do not match the frozen protocol. ' ...
     'Expected 20261001:20261005.']);

assert(isequal(confirmSeeds,20270001:20270030), ...
    ['Confirmation seeds do not match the frozen protocol. ' ...
     'Expected 20270001:20270030.']);

assert(isempty(intersect(devSeeds,confirmSeeds)), ...
    'DEV and CONFIRM seeds overlap.');

assert(numel(devSeeds)==5, ...
    'Expected exactly five DEV seeds.');

assert(numel(scenarios)==4, ...
    'Expected exactly four synthetic scenarios.');

% Frozen HCL identity checks
assert(abs(C.hcl.epsWarm-1e-2)<1e-14, ...
    'epsWarm changed.');

assert(abs(C.hcl.epsSel-1e-2)<1e-14, ...
    'epsSel changed.');

assert(abs(C.hcl.epsRec-1e-3)<1e-14, ...
    'epsRec changed.');

assert(C.hcl.b==8, ...
    'Block scale b changed.');

assert(abs(C.hcl.tauHigh-0.90)<1e-14, ...
    'tauHigh changed.');

assert(abs(C.hcl.fMax-0.32)<1e-14, ...
    'fMax changed.');

assert(abs(C.hcl.etaMin-0.68)<1e-14, ...
    'etaMin changed.');

assert(abs(C.hcl.gamma-0.85)<1e-14, ...
    'gamma changed.');

assert(abs(C.hcl.relTol-1e-5)<1e-14, ...
    'relTol changed.');

fprintf('DEV seeds     : %d -- %d\n', ...
    devSeeds(1),devSeeds(end));

fprintf('CONFIRM seeds : %d -- %d\n', ...
    confirmSeeds(1),confirmSeeds(end));

fprintf('Scenarios     : EB / ES / BS / EBS\n');
fprintf('Expected files: %d\n\n', ...
    numel(devSeeds)*numel(scenarios));

%% ============================================================
% 3. Independent output directory
% =============================================================

outDir = fullfile( ...
    C.outputRoot, ...
    'E00_ATTRIBUTION_DEV');

if ~exist(outDir,'dir')
    mkdir(outDir);
end

fprintf('Output:\n%s\n\n',outDir);

%% ============================================================
% 4. Run ONLY frozen HCL
% =============================================================

rows = cell( ...
    numel(devSeeds)*numel(scenarios), ...
    10);

rid = 0;

for iseed = 1:numel(devSeeds)

    seed = devSeeds(iseed);

    for is = 1:numel(scenarios)

        sc = scenarios{is};

        fprintf('------------------------------------------------------------\n');
        fprintf('[DEV] seed %d | %s\n',seed,sc);

        %% Same synthetic generator as CONFIRMATION
        D = hcl_synthetic_case( ...
            seed, ...
            sc, ...
            C, ...
            'DISJOINT');

        %% Same frozen HCL solver as CONFIRMATION
        H = hcl_trpca_final( ...
            D.Y, ...
            D.rank, ...
            C.hcl);

        %% Same metric function as CONFIRMATION
        M = hcl_metrics( ...
            H.Xhat, ...
            D, ...
            H);

        %% Save in EXACTLY the same D/H/M state format
        runDir = fullfile( ...
            outDir, ...
            sprintf('seed_%d',seed), ...
            sc);

        if ~exist(runDir,'dir')
            mkdir(runDir);
        end

        stateFile = fullfile( ...
            runDir, ...
            'HCL_state.mat');

        save( ...
            stateFile, ...
            'D', ...
            'H', ...
            'M', ...
            '-v7.3');

        %% Immediate integrity check
        W = whos('-file',stateFile);
        savedNames = string({W.name});

        assert(all(ismember(["D","H","M"],savedNames)), ...
            'Saved DEV state is missing D/H/M: %s', ...
            stateFile);

        rid = rid + 1;

        rows(rid,:) = { ...
            seed, ...
            string(sc), ...
            M.NRE, ...
            M.DetF1, ...
            M.MaskF1, ...
            M.LevelMacroF1, ...
            H.recoveryESS, ...
            H.selectedFraction, ...
            H.iterations, ...
            string(stateFile)};

        fprintf(['Saved | NRE=%.6f | DetF1=%.4f | ' ...
                 'MaskF1=%.4f | LevelF1=%.4f\n'], ...
            M.NRE, ...
            M.DetF1, ...
            M.MaskF1, ...
            M.LevelMacroF1);

    end
end

%% ============================================================
% 5. Development manifest
% =============================================================

T = cell2table( ...
    rows, ...
    'VariableNames', { ...
    'Seed', ...
    'Scenario', ...
    'NRE', ...
    'DetectionF1', ...
    'RecoveryMaskF1', ...
    'LevelMacroF1', ...
    'rESS', ...
    'SelectedFraction', ...
    'Iterations', ...
    'StateFile'});

writetable( ...
    T, ...
    fullfile(outDir,'attribution_dev_manifest.csv'));

%% ============================================================
% 6. Hard file-count audit
% =============================================================

F = dir(fullfile( ...
    outDir, ...
    'seed_*', ...
    '*', ...
    'HCL_state.mat'));

fprintf('\n============================================================\n');
fprintf('DEV GENERATION SUMMARY\n');
fprintf('============================================================\n');

fprintf('Expected HCL_state.mat : 20\n');
fprintf('Found HCL_state.mat    : %d\n',numel(F));

assert(numel(F)==20, ...
    ['DEV generation incomplete: expected 20 HCL_state.mat ' ...
     'files but found %d.'], ...
    numel(F));

fprintf('\nDEV STATE GENERATION: PASS\n');
fprintf('============================================================\n');

R = struct();
R.raw = T;
R.outputDir = outDir;
R.expectedStates = 20;
R.actualStates = numel(F);
R.devSeeds = devSeeds;
R.scenarios = scenarios;

save( ...
    fullfile(outDir,'attribution_dev_results.mat'), ...
    'R');

end