function report = audit_sbi_release_semantics()
%AUDIT_SBI_RELEASE_SEMANTICS Validate the archived v1.0.1 SBI semantics.
% This audit uses only the compact release artifacts and requires no raw
% dataset or external solver.

repoRoot = setup_hcl_trpca();
summaryFile = fullfile( ...
    repoRoot, 'results', 'sbi', 'sbi_final_summary.csv');
compactFile = fullfile( ...
    repoRoot, 'results', 'sbi', 'SBI_review_small.mat');

assert(isfile(summaryFile), 'Missing archived SBI summary: %s', summaryFile);
assert(isfile(compactFile), 'Missing compact SBI MAT file: %s', compactFile);

textColumns = {'Dataset', 'GroundTruthType', ...
    'ReconstructionMetricsStatus'};
numericColumns = { ...
    'Height', 'Width', 'Frames', 'Rank', ...
    'SelectedFraction', 'rESS', 'Iterations', 'FinalRelChange', ...
    'ToleranceMet', 'HasAnnotation', 'HasSegmentationGT', ...
    'SpatialAlignmentVerified', 'FrameIndexAlignmentVerified', ...
    'HasCleanReference', 'ValidReconstructionReference', ...
    'PSNR', 'SSIM', 'AGE'};
importOptions = detectImportOptions(summaryFile, 'TextType', 'string');
importOptions = setvartype(importOptions, textColumns, 'string');
importOptions = setvartype(importOptions, numericColumns, 'double');
T = readtable(summaryFile, importOptions);
requiredColumns = { ...
    'Dataset', ...
    'Height', ...
    'Width', ...
    'Frames', ...
    'Rank', ...
    'SelectedFraction', ...
    'rESS', ...
    'Iterations', ...
    'FinalRelChange', ...
    'ToleranceMet', ...
    'HasAnnotation', ...
    'HasSegmentationGT', ...
    'SpatialAlignmentVerified', ...
    'FrameIndexAlignmentVerified', ...
    'HasCleanReference', ...
    'ValidReconstructionReference', ...
    'GroundTruthType', ...
    'PSNR', ...
    'SSIM', ...
    'AGE', ...
    'ReconstructionMetricsStatus'};

assert(all(ismember(requiredColumns, T.Properties.VariableNames)), ...
    'The archived SBI CSV is missing v1.0.1 semantic fields.');
assert(height(T) == 4, 'Expected four archived SBI sequences.');
assert(all(isnan(T.PSNR)) && all(isnan(T.SSIM)) && all(isnan(T.AGE)), ...
    'Archived SBI reconstruction metrics must be NaN.');
assert(~any(logical(T.HasCleanReference)), ...
    'No archived SBI sequence has a clean-background reference.');
assert(~any(logical(T.ValidReconstructionReference)), ...
    'No archived SBI sequence has a valid reconstruction reference.');

maskRows = ismember(T.Dataset, ["SBI_Board", "SBI_CAVIAR1"]);
assert(sum(maskRows) == 2, 'Board or CAVIAR1 is missing from the SBI CSV.');
assert(all(logical(T.HasSegmentationGT(maskRows))), ...
    'Board and CAVIAR1 must be identified as segmentation annotations.');
assert(all(T.GroundTruthType(maskRows) == ...
    "foreground_segmentation_mask"), ...
    'Board and CAVIAR1 have an invalid ground-truth type.');

loaded = load(compactFile, 'Review');
assert(isfield(loaded, 'Review') && isstruct(loaded.Review), ...
    'The compact SBI MAT file does not contain Review.');

sequenceNames = { ...
    'SBI_Board', ...
    'SBI_CAVIAR1', ...
    'SBI_Hall_Monitor', ...
    'SBI_People_Foliage'};
semanticFields = { ...
    'hasAnnotation', ...
    'hasSegmentationGT', ...
    'spatialAlignmentVerified', ...
    'frameIndexAlignmentVerified', ...
    'groundTruthType', ...
    'hasCleanReference', ...
    'validReconstructionReference', ...
    'reconstructionMetricsStatus'};

for i = 1:numel(sequenceNames)
    name = sequenceNames{i};
    assert(isfield(loaded.Review, name), ...
        'Missing compact SBI record: %s', name);
    R = loaded.Review.(name);
    assert(~isfield(R, 'hasGT'), ...
        'Legacy ambiguous field hasGT remains in %s.', name);
    assert(all(isfield(R, semanticFields)), ...
        'A v1.0.1 semantic field is missing from %s.', name);
    assert(~logical(R.hasCleanReference), ...
        '%s incorrectly declares a clean reference.', name);
    assert(~logical(R.validReconstructionReference), ...
        '%s incorrectly declares a valid reconstruction reference.', name);

    row = find(T.Dataset == string(name), 1);
    assert(~isempty(row), 'Missing CSV row for %s.', name);
    assert(R.rank == T.Rank(row), 'Rank mismatch for %s.', name);
    assert(abs(R.selectedFraction - T.SelectedFraction(row)) < 1e-14, ...
        'SelectedFraction mismatch for %s.', name);
    assert(abs(R.recoveryESS - T.rESS(row)) < 1e-14, ...
        'rESS mismatch for %s.', name);
    assert(R.iterations == T.Iterations(row), ...
        'Iteration mismatch for %s.', name);
    assert(abs(R.finalRelChange - T.FinalRelChange(row)) < 1e-14, ...
        'FinalRelChange mismatch for %s.', name);
    assert(logical(R.toleranceMet) == logical(T.ToleranceMet(row)), ...
        'ToleranceMet mismatch for %s.', name);
end

report = struct();
report.pass = true;
report.sequenceCount = height(T);
report.validReconstructionReferenceCount = ...
    sum(logical(T.ValidReconstructionReference));
report.numericReconstructionMetricCount = ...
    sum(~isnan(T.PSNR)) + sum(~isnan(T.SSIM)) + sum(~isnan(T.AGE));

fprintf('\n=== SBI RELEASE-SEMANTICS AUDIT ===\n');
fprintf('Sequences: %d\n', report.sequenceCount);
fprintf('Valid reconstruction references: %d\n', ...
    report.validReconstructionReferenceCount);
fprintf('Numeric reconstruction metrics: %d\n', ...
    report.numericReconstructionMetricCount);
fprintf('SBI semantic audit: PASS\n');
end
